name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # 允许写入内容（包括 gh-pages 分支）
  pages: write     # 允许写入 GitHub Pages
  id-token: write  # 允许写入 ID token

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      # 提前下载 Twikoo（在构建之后，部署之前）
      - name: Download Twikoo
        run: |
          mkdir -p ./themes/DoIt/assets/lib/twikoo/
          curl -L https://cdn.jsdelivr.net/npm/twikoo@1.6.20/dist/twikoo.all.min.js \
            -o ./themes/DoIt/assets/lib/twikoo/twikoo.all.min.js
        # 可选：重新构建以包含 Twikoo
        # run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          # ✅ 改用 GITHUB_TOKEN（推荐）
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          force_orphan: true